name: Nightly Build

on:
  schedule:
    - cron: 45 4 * * *

  workflow_dispatch:

env:
  # todo: Replace following envs with vars see https://github.com/community/community/discussions/44322
  GCLOUD_BUCKET: test-lab-9c68imc4w11aa-i4k7hbj489wyu
  GCLOUD_SERVICE_ACCOUNT: test-restults-fetcher@gnucash-pocket.iam.gserviceaccount.com
  GCLOUD_WORKLOAD_IDENTITY_PROVIDER: projects/679335683580/locations/global/workloadIdentityPools/github-main-testing-pool/providers/github

jobs:
  ci-build:
    uses: ./.github/workflows/ci-build.yml

  report-unit:
    uses: ./.github/workflows/report-unit.yml
    needs: ci-build

  
